export const userData = [
    {
      name: 'Jan',
      "Active": 4000,
    },
    {
      name: 'Feb',
      "Active": 3000,
    },
    {
      name: 'Mar',
      "Active": 2000,
    },
    {
      name: 'Apr',
      "Active": 2780,
    },
    {
      name: 'May',
      "Active": 1890,
    },
    {
      name: 'jun',
      "Active": 2390,
    },
    {
      name: 'jul',
      "Active": 3490,
    },
    {
        name: 'Aug',
        "Active": 1500,
      },
      {
        name: 'Sep',
        "Active": 3222,
      },
      {
        name: 'Oct',
        "Active": 4100,
      },
      {
        name: 'Nov',
        "Active": 2678,
      },
      {
        name: 'Dec',
        "Active": 3000,
      },
  ];

  export const userRows = [
    { id: 1, 
      username: 'Sakshi', 
      avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
      email: "sakshi@gmail.com" ,
      status:"active",
      transaction: "Rs. 5000",
    },
    { id: 2, 
        username: 'Avani', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 4390",
      },
      { id: 3, 
        username: 'Jinisha', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 8700",
      },
      { id: 4, 
        username: 'Arzoo', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 4000",
      },
      { id: 5, 
        username: 'Arav', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 2000",
      },
      { id: 6, 
        username: 'Sakshi', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 9000",
      },
      { id: 7, 
        username: 'Honey', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 6500",
      },
      { id: 8, 
        username: 'Vikas', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 8500",
      },
      { id: 9, 
        username: 'Anshima', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"Inactive",
        transaction: "Rs. 3800",
      },
      { id: 10, 
        username: 'Aditya', 
        avtar: "https://thumbs.dreamstime.com/b/businesswoman-avatar-cartoon-character-profile-picture-short-hair-portrait-round-icon-vector-illustration-graphic-design-149146952.jpg",
        email: "sakshi@gmail.com" ,
        status:"active",
        transaction: "Rs. 6600",
      },
  ];


  export const productRows = [
    { id: 1, 
      name : 'i-pad', 
      img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
      stock: 123,
      Price: "Rs. 67,000",
    },
    { id: 2, 
        name : 'i-phone 12', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 456 ,
        transaction: "Rs. 64390",
      },
      { id: 3, 
        name : 'google pixel', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 230 ,
        transaction: "Rs. 88700",
      },
      { id: 4, 
        name : 'i-phone 12', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 600 ,
        transaction: "Rs. 84000",
      },
      { id: 5, 
        name : 'airpodes', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 100 ,
        transaction: "Rs. 12000",
      },
      { id: 6, 
        name : 'google pixel', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 700 ,
        transaction: "Rs. 69000",
      },
      { id: 7, 
        name : 'hp laptop', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 234 ,
        transaction: "Rs. 65000",
      },
      { id: 8, 
        name : 'i-pad', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 300 ,
        transaction: "Rs. 58500",
      },
      { id: 9, 
        name : 'redmi note 9', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 134 ,
        transaction: "Rs. 14,000",
      },
      { id: 10, 
        name : 'smart watch', 
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1skAh3KI1XWVo8IFDjrep6VLPqh7TiF8rQ&usqp=CAU",
        stock: 544 ,
        transaction: "Rs. 6600",
      },
  ];

  export const productData = [
    {
      name: 'Mon',
      "Sales": 4000,
    },
    {
      name: 'Tue',
      "Sales": 3200,
    },
    {
      name: 'Wed',
      "Sales": 2050,
    },
    {
      name: 'Thur',
      "Sales": 2780,
    },
    {
      name: 'Fri',
      "Sales": 1890,
    },
    {
      name: 'Sat',
      "Sales": 6390,
    },
    {
      name: 'Sun',
      "Sales": 4490,
    },
   
      
  ];

